version: '3.8'

services:
  sodai-airflow:
    build: .
    container_name: sodai-airflow
    ports:
      - "8080:8080"
    networks:
      - sodai-network
    volumes:
      - sodai-shared-data:/shared-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 

networks:
  sodai-network:
    external: true

volumes:
  sodai-shared-data:
    external: true